// generated by gen_classids -classes ./classes.txt -output ./classids.go; DO NOT EDIT

package unity

import "fmt"

const (
	Null                         ClassID = 0
	GameObject                   ClassID = 1
	Component                    ClassID = 2
	LevelGameManager             ClassID = 3
	Transform                    ClassID = 4
	TimeManager                  ClassID = 5
	GlobalGameManager            ClassID = 6
	Behaviour                    ClassID = 8
	GameManager                  ClassID = 9
	AudioManager                 ClassID = 11
	ParticleAnimator             ClassID = 12
	InputManager                 ClassID = 13
	EllipsoidParticleEmitter     ClassID = 15
	Pipeline                     ClassID = 17
	EditorExtension              ClassID = 18
	Physics2DSettings            ClassID = 19
	Camera                       ClassID = 20
	Material                     ClassID = 21
	MeshRenderer                 ClassID = 23
	Renderer                     ClassID = 25
	ParticleRenderer             ClassID = 26
	Texture                      ClassID = 27
	Texture2D                    ClassID = 28
	SceneSettings                ClassID = 29
	GraphicsSettings             ClassID = 30
	MeshFilter                   ClassID = 33
	OcclusionPortal              ClassID = 41
	Mesh                         ClassID = 43
	Skybox                       ClassID = 45
	QualitySettings              ClassID = 47
	Shader                       ClassID = 48
	TextAsset                    ClassID = 49
	Rigidbody2D                  ClassID = 50
	Physics2DManager             ClassID = 51
	Collider2D                   ClassID = 53
	Rigidbody                    ClassID = 54
	PhysicsManager               ClassID = 55
	Collider                     ClassID = 56
	Joint                        ClassID = 57
	CircleCollider2D             ClassID = 58
	HingeJoint                   ClassID = 59
	PolygonCollider2D            ClassID = 60
	BoxCollider2D                ClassID = 61
	PhysicsMaterial2D            ClassID = 62
	MeshCollider                 ClassID = 64
	BoxCollider                  ClassID = 65
	SpriteCollider2D             ClassID = 66
	EdgeCollider2D               ClassID = 68
	ComputeShader                ClassID = 72
	AnimationClip                ClassID = 74
	ConstantForce                ClassID = 75
	WorldParticleCollider        ClassID = 76
	TagManager                   ClassID = 78
	AudioListener                ClassID = 81
	AudioSource                  ClassID = 82
	AudioClip                    ClassID = 83
	RenderTexture                ClassID = 84
	MeshParticleEmitter          ClassID = 87
	ParticleEmitter              ClassID = 88
	Cubemap                      ClassID = 89
	Avatar                       ClassID = 90
	AnimatorController           ClassID = 91
	GUILayer                     ClassID = 92
	RuntimeAnimatorController    ClassID = 93
	ScriptMapper                 ClassID = 94
	Animator                     ClassID = 95
	TrailRenderer                ClassID = 96
	DelayedCallManager           ClassID = 98
	TextMesh                     ClassID = 102
	RenderSettings               ClassID = 104
	Light                        ClassID = 108
	CGProgram                    ClassID = 109
	BaseAnimationTrack           ClassID = 110
	Animation                    ClassID = 111
	MonoBehaviour                ClassID = 114
	MonoScript                   ClassID = 115
	MonoManager                  ClassID = 116
	Texture3D                    ClassID = 117
	NewAnimationTrack            ClassID = 118
	Projector                    ClassID = 119
	LineRenderer                 ClassID = 120
	Flare                        ClassID = 121
	Halo                         ClassID = 122
	LensFlare                    ClassID = 123
	FlareLayer                   ClassID = 124
	HaloLayer                    ClassID = 125
	NavMeshAreas                 ClassID = 126
	HaloManager                  ClassID = 127
	Font                         ClassID = 128
	PlayerSettings               ClassID = 129
	NamedObject                  ClassID = 130
	GUITexture                   ClassID = 131
	GUIText                      ClassID = 132
	GUIElement                   ClassID = 133
	PhysicMaterial               ClassID = 134
	SphereCollider               ClassID = 135
	CapsuleCollider              ClassID = 136
	SkinnedMeshRenderer          ClassID = 137
	FixedJoint                   ClassID = 138
	RaycastCollider              ClassID = 140
	BuildSettings                ClassID = 141
	AssetBundle                  ClassID = 142
	CharacterController          ClassID = 143
	CharacterJoint               ClassID = 144
	SpringJoint                  ClassID = 145
	WheelCollider                ClassID = 146
	ResourceManager              ClassID = 147
	NetworkView                  ClassID = 148
	NetworkManager               ClassID = 149
	PreloadData                  ClassID = 150
	MovieTexture                 ClassID = 152
	ConfigurableJoint            ClassID = 153
	TerrainCollider              ClassID = 154
	MasterServerInterface        ClassID = 155
	TerrainData                  ClassID = 156
	LightmapSettings             ClassID = 157
	WebCamTexture                ClassID = 158
	EditorSettings               ClassID = 159
	InteractiveCloth             ClassID = 160
	ClothRenderer                ClassID = 161
	EditorUserSettings           ClassID = 162
	SkinnedCloth                 ClassID = 163
	AudioReverbFilter            ClassID = 164
	AudioHighPassFilter          ClassID = 165
	AudioChorusFilter            ClassID = 166
	AudioReverbZone              ClassID = 167
	AudioEchoFilter              ClassID = 168
	AudioLowPassFilter           ClassID = 169
	AudioDistortionFilter        ClassID = 170
	SparseTexture                ClassID = 171
	AudioBehaviour               ClassID = 180
	AudioFilter                  ClassID = 181
	WindZone                     ClassID = 182
	Cloth                        ClassID = 183
	SubstanceArchive             ClassID = 184
	ProceduralMaterial           ClassID = 185
	ProceduralTexture            ClassID = 186
	OffMeshLink                  ClassID = 191
	OcclusionArea                ClassID = 192
	Tree                         ClassID = 193
	NavMeshObsolete              ClassID = 194
	NavMeshAgent                 ClassID = 195
	NavMeshSettings              ClassID = 196
	LightProbesLegacy            ClassID = 197
	ParticleSystem               ClassID = 198
	ParticleSystemRenderer       ClassID = 199
	ShaderVariantCollection      ClassID = 200
	LODGroup                     ClassID = 205
	BlendTree                    ClassID = 206
	Motion                       ClassID = 207
	NavMeshObstacle              ClassID = 208
	TerrainInstance              ClassID = 210
	SpriteRenderer               ClassID = 212
	Sprite                       ClassID = 213
	CachedSpriteAtlas            ClassID = 214
	ReflectionProbe              ClassID = 215
	ReflectionProbes             ClassID = 216
	LightProbeGroup              ClassID = 220
	AnimatorOverrideController   ClassID = 221
	CanvasRenderer               ClassID = 222
	Canvas                       ClassID = 223
	RectTransform                ClassID = 224
	CanvasGroup                  ClassID = 225
	BillboardAsset               ClassID = 226
	BillboardRenderer            ClassID = 227
	SpeedTreeWindAsset           ClassID = 228
	AnchoredJoint2D              ClassID = 229
	Joint2D                      ClassID = 230
	SpringJoint2D                ClassID = 231
	DistanceJoint2D              ClassID = 232
	HingeJoint2D                 ClassID = 233
	SliderJoint2D                ClassID = 234
	WheelJoint2D                 ClassID = 235
	NavMeshData                  ClassID = 238
	AudioMixer                   ClassID = 240
	AudioMixerController         ClassID = 241
	AudioMixerGroupController    ClassID = 243
	AudioMixerEffectController   ClassID = 244
	AudioMixerSnapshotController ClassID = 245
	PhysicsUpdateBehaviour2D     ClassID = 246
	ConstantForce2D              ClassID = 247
	Effector2D                   ClassID = 248
	AreaEffector2D               ClassID = 249
	PointEffector2D              ClassID = 250
	PlatformEffector2D           ClassID = 251
	SurfaceEffector2D            ClassID = 252
	LightProbes                  ClassID = 258
	SampleClip                   ClassID = 271
	AudioMixerSnapshot           ClassID = 272
	AudioMixerGroup              ClassID = 273
	AssetBundleManifest          ClassID = 290
	Prefab                       ClassID = 1001
	EditorExtensionImpl          ClassID = 1002
	AssetImporter                ClassID = 1003
	AssetDatabase                ClassID = 1004
	Mesh3DSImporter              ClassID = 1005
	TextureImporter              ClassID = 1006
	ShaderImporter               ClassID = 1007
	ComputeShaderImporter        ClassID = 1008
	AvatarMask                   ClassID = 1011
	AudioImporter                ClassID = 1020
	HierarchyState               ClassID = 1026
	GUIDSerializer               ClassID = 1027
	AssetMetaData                ClassID = 1028
	DefaultAsset                 ClassID = 1029
	DefaultImporter              ClassID = 1030
	TextScriptImporter           ClassID = 1031
	SceneAsset                   ClassID = 1032
	NativeFormatImporter         ClassID = 1034
	MonoImporter                 ClassID = 1035
	AssetServerCache             ClassID = 1037
	LibraryAssetImporter         ClassID = 1038
	ModelImporter                ClassID = 1040
	FBXImporter                  ClassID = 1041
	TrueTypeFontImporter         ClassID = 1042
	MovieImporter                ClassID = 1044
	EditorBuildSettings          ClassID = 1045
	DDSImporter                  ClassID = 1046
	InspectorExpandedState       ClassID = 1048
	AnnotationManager            ClassID = 1049
	PluginImporter               ClassID = 1050
	EditorUserBuildSettings      ClassID = 1051
	PVRImporter                  ClassID = 1052
	ASTCImporter                 ClassID = 1053
	KTXImporter                  ClassID = 1054
	AnimatorStateTransition      ClassID = 1101
	AnimatorState                ClassID = 1102
	HumanTemplate                ClassID = 1105
	AnimatorStateMachine         ClassID = 1107
	PreviewAssetType             ClassID = 1108
	AnimatorTransition           ClassID = 1109
	SpeedTreeImporter            ClassID = 1110
	AnimatorTransitionBase       ClassID = 1111
	SubstanceImporter            ClassID = 1112
	LightmapParameters           ClassID = 1113
	LightmapSnapshot             ClassID = 1120
)

func (c ClassID) String() string {
	switch c {
	case 1:
		return "GameObject"
	case 2:
		return "Component"
	case 3:
		return "LevelGameManager"
	case 4:
		return "Transform"
	case 5:
		return "TimeManager"
	case 6:
		return "GlobalGameManager"
	case 8:
		return "Behaviour"
	case 9:
		return "GameManager"
	case 11:
		return "AudioManager"
	case 12:
		return "ParticleAnimator"
	case 13:
		return "InputManager"
	case 15:
		return "EllipsoidParticleEmitter"
	case 17:
		return "Pipeline"
	case 18:
		return "EditorExtension"
	case 19:
		return "Physics2DSettings"
	case 20:
		return "Camera"
	case 21:
		return "Material"
	case 23:
		return "MeshRenderer"
	case 25:
		return "Renderer"
	case 26:
		return "ParticleRenderer"
	case 27:
		return "Texture"
	case 28:
		return "Texture2D"
	case 29:
		return "SceneSettings"
	case 30:
		return "GraphicsSettings"
	case 33:
		return "MeshFilter"
	case 41:
		return "OcclusionPortal"
	case 43:
		return "Mesh"
	case 45:
		return "Skybox"
	case 47:
		return "QualitySettings"
	case 48:
		return "Shader"
	case 49:
		return "TextAsset"
	case 50:
		return "Rigidbody2D"
	case 51:
		return "Physics2DManager"
	case 53:
		return "Collider2D"
	case 54:
		return "Rigidbody"
	case 55:
		return "PhysicsManager"
	case 56:
		return "Collider"
	case 57:
		return "Joint"
	case 58:
		return "CircleCollider2D"
	case 59:
		return "HingeJoint"
	case 60:
		return "PolygonCollider2D"
	case 61:
		return "BoxCollider2D"
	case 62:
		return "PhysicsMaterial2D"
	case 64:
		return "MeshCollider"
	case 65:
		return "BoxCollider"
	case 66:
		return "SpriteCollider2D"
	case 68:
		return "EdgeCollider2D"
	case 72:
		return "ComputeShader"
	case 74:
		return "AnimationClip"
	case 75:
		return "ConstantForce"
	case 76:
		return "WorldParticleCollider"
	case 78:
		return "TagManager"
	case 81:
		return "AudioListener"
	case 82:
		return "AudioSource"
	case 83:
		return "AudioClip"
	case 84:
		return "RenderTexture"
	case 87:
		return "MeshParticleEmitter"
	case 88:
		return "ParticleEmitter"
	case 89:
		return "Cubemap"
	case 90:
		return "Avatar"
	case 91:
		return "AnimatorController"
	case 92:
		return "GUILayer"
	case 93:
		return "RuntimeAnimatorController"
	case 94:
		return "ScriptMapper"
	case 95:
		return "Animator"
	case 96:
		return "TrailRenderer"
	case 98:
		return "DelayedCallManager"
	case 102:
		return "TextMesh"
	case 104:
		return "RenderSettings"
	case 108:
		return "Light"
	case 109:
		return "CGProgram"
	case 110:
		return "BaseAnimationTrack"
	case 111:
		return "Animation"
	case 114:
		return "MonoBehaviour"
	case 115:
		return "MonoScript"
	case 116:
		return "MonoManager"
	case 117:
		return "Texture3D"
	case 118:
		return "NewAnimationTrack"
	case 119:
		return "Projector"
	case 120:
		return "LineRenderer"
	case 121:
		return "Flare"
	case 122:
		return "Halo"
	case 123:
		return "LensFlare"
	case 124:
		return "FlareLayer"
	case 125:
		return "HaloLayer"
	case 126:
		return "NavMeshAreas"
	case 127:
		return "HaloManager"
	case 128:
		return "Font"
	case 129:
		return "PlayerSettings"
	case 130:
		return "NamedObject"
	case 131:
		return "GUITexture"
	case 132:
		return "GUIText"
	case 133:
		return "GUIElement"
	case 134:
		return "PhysicMaterial"
	case 135:
		return "SphereCollider"
	case 136:
		return "CapsuleCollider"
	case 137:
		return "SkinnedMeshRenderer"
	case 138:
		return "FixedJoint"
	case 140:
		return "RaycastCollider"
	case 141:
		return "BuildSettings"
	case 142:
		return "AssetBundle"
	case 143:
		return "CharacterController"
	case 144:
		return "CharacterJoint"
	case 145:
		return "SpringJoint"
	case 146:
		return "WheelCollider"
	case 147:
		return "ResourceManager"
	case 148:
		return "NetworkView"
	case 149:
		return "NetworkManager"
	case 150:
		return "PreloadData"
	case 152:
		return "MovieTexture"
	case 153:
		return "ConfigurableJoint"
	case 154:
		return "TerrainCollider"
	case 155:
		return "MasterServerInterface"
	case 156:
		return "TerrainData"
	case 157:
		return "LightmapSettings"
	case 158:
		return "WebCamTexture"
	case 159:
		return "EditorSettings"
	case 160:
		return "InteractiveCloth"
	case 161:
		return "ClothRenderer"
	case 162:
		return "EditorUserSettings"
	case 163:
		return "SkinnedCloth"
	case 164:
		return "AudioReverbFilter"
	case 165:
		return "AudioHighPassFilter"
	case 166:
		return "AudioChorusFilter"
	case 167:
		return "AudioReverbZone"
	case 168:
		return "AudioEchoFilter"
	case 169:
		return "AudioLowPassFilter"
	case 170:
		return "AudioDistortionFilter"
	case 171:
		return "SparseTexture"
	case 180:
		return "AudioBehaviour"
	case 181:
		return "AudioFilter"
	case 182:
		return "WindZone"
	case 183:
		return "Cloth"
	case 184:
		return "SubstanceArchive"
	case 185:
		return "ProceduralMaterial"
	case 186:
		return "ProceduralTexture"
	case 191:
		return "OffMeshLink"
	case 192:
		return "OcclusionArea"
	case 193:
		return "Tree"
	case 194:
		return "NavMeshObsolete"
	case 195:
		return "NavMeshAgent"
	case 196:
		return "NavMeshSettings"
	case 197:
		return "LightProbesLegacy"
	case 198:
		return "ParticleSystem"
	case 199:
		return "ParticleSystemRenderer"
	case 200:
		return "ShaderVariantCollection"
	case 205:
		return "LODGroup"
	case 206:
		return "BlendTree"
	case 207:
		return "Motion"
	case 208:
		return "NavMeshObstacle"
	case 210:
		return "TerrainInstance"
	case 212:
		return "SpriteRenderer"
	case 213:
		return "Sprite"
	case 214:
		return "CachedSpriteAtlas"
	case 215:
		return "ReflectionProbe"
	case 216:
		return "ReflectionProbes"
	case 220:
		return "LightProbeGroup"
	case 221:
		return "AnimatorOverrideController"
	case 222:
		return "CanvasRenderer"
	case 223:
		return "Canvas"
	case 224:
		return "RectTransform"
	case 225:
		return "CanvasGroup"
	case 226:
		return "BillboardAsset"
	case 227:
		return "BillboardRenderer"
	case 228:
		return "SpeedTreeWindAsset"
	case 229:
		return "AnchoredJoint2D"
	case 230:
		return "Joint2D"
	case 231:
		return "SpringJoint2D"
	case 232:
		return "DistanceJoint2D"
	case 233:
		return "HingeJoint2D"
	case 234:
		return "SliderJoint2D"
	case 235:
		return "WheelJoint2D"
	case 238:
		return "NavMeshData"
	case 240:
		return "AudioMixer"
	case 241:
		return "AudioMixerController"
	case 243:
		return "AudioMixerGroupController"
	case 244:
		return "AudioMixerEffectController"
	case 245:
		return "AudioMixerSnapshotController"
	case 246:
		return "PhysicsUpdateBehaviour2D"
	case 247:
		return "ConstantForce2D"
	case 248:
		return "Effector2D"
	case 249:
		return "AreaEffector2D"
	case 250:
		return "PointEffector2D"
	case 251:
		return "PlatformEffector2D"
	case 252:
		return "SurfaceEffector2D"
	case 258:
		return "LightProbes"
	case 271:
		return "SampleClip"
	case 272:
		return "AudioMixerSnapshot"
	case 273:
		return "AudioMixerGroup"
	case 290:
		return "AssetBundleManifest"
	case 1001:
		return "Prefab"
	case 1002:
		return "EditorExtensionImpl"
	case 1003:
		return "AssetImporter"
	case 1004:
		return "AssetDatabase"
	case 1005:
		return "Mesh3DSImporter"
	case 1006:
		return "TextureImporter"
	case 1007:
		return "ShaderImporter"
	case 1008:
		return "ComputeShaderImporter"
	case 1011:
		return "AvatarMask"
	case 1020:
		return "AudioImporter"
	case 1026:
		return "HierarchyState"
	case 1027:
		return "GUIDSerializer"
	case 1028:
		return "AssetMetaData"
	case 1029:
		return "DefaultAsset"
	case 1030:
		return "DefaultImporter"
	case 1031:
		return "TextScriptImporter"
	case 1032:
		return "SceneAsset"
	case 1034:
		return "NativeFormatImporter"
	case 1035:
		return "MonoImporter"
	case 1037:
		return "AssetServerCache"
	case 1038:
		return "LibraryAssetImporter"
	case 1040:
		return "ModelImporter"
	case 1041:
		return "FBXImporter"
	case 1042:
		return "TrueTypeFontImporter"
	case 1044:
		return "MovieImporter"
	case 1045:
		return "EditorBuildSettings"
	case 1046:
		return "DDSImporter"
	case 1048:
		return "InspectorExpandedState"
	case 1049:
		return "AnnotationManager"
	case 1050:
		return "PluginImporter"
	case 1051:
		return "EditorUserBuildSettings"
	case 1052:
		return "PVRImporter"
	case 1053:
		return "ASTCImporter"
	case 1054:
		return "KTXImporter"
	case 1101:
		return "AnimatorStateTransition"
	case 1102:
		return "AnimatorState"
	case 1105:
		return "HumanTemplate"
	case 1107:
		return "AnimatorStateMachine"
	case 1108:
		return "PreviewAssetType"
	case 1109:
		return "AnimatorTransition"
	case 1110:
		return "SpeedTreeImporter"
	case 1111:
		return "AnimatorTransitionBase"
	case 1112:
		return "SubstanceImporter"
	case 1113:
		return "LightmapParameters"
	case 1120:
		return "LightmapSnapshot"
	default:
		panic(fmt.Errorf("Unexpected ClassID: %d", c))
	}
}
